### ISSUE TITLE
Unable to restore wallet

### ISSUE THREAD

**Issue by InstaZDLL** [mrmikeo/pandanite-wallet#1]
I created an account, closed the app and opened it later. Impossible to connect it tells me impossible to join the node and when I restore with the 12 words nothing works I wait 30 min and still nothing, then I restored with the public key and private nothing works either, WHAT THE HELL, HELP ME!

![Screenshot 2023-06-08 221059](https://github.com/pandanite-crypto/pandanite-wallet/assets/72951793/3547dca0-a29e-486d-8997-2adfd6084e6d)

**Comment by InstaZDLL** [comment]
I've tried uninstalling and reinstalling the application, but nothing works.

**Comment by InstaZDLL** [comment]
I'm on windows 11

**Comment by InstaZDLL** [comment]
![Screenshot 2023-06-08 222201](https://github.com/pandanite-crypto/pandanite-wallet/assets/72951793/8a1c3ee0-e391-4266-9be2-d2c241d21113)

**Comment by InstaZDLL** [comment]
Even if I enter https://pandanite.net, it doesn't work.

**Comment by InstaZDLL** [comment]
I tried to create a new wallet to see, I created it and closed the application, when I open it again and enter the password I get the same popup has here [here](https://github.com/pandanite-crypto/pandanite-wallet/issues/1#issuecomment-1583287996)

**Comment by InstaZDLL** [comment]
I can see that this might be why it doesn't work.
![Screenshot 2023-06-08 222530](https://github.com/pandanite-crypto/pandanite-wallet/assets/72951793/3ea17116-3181-42d2-b5ee-429288a2b055)

**Comment by netrucho** [comment]
> ![Screenshot 2023-06-08 222201](https://user-images.githubusercontent.com/72951793/244495509-8a1c3ee0-e391-4266-9be2-d2c241d21113.png)

open port 3000 on your router

**Comment by InstaZDLL** [comment]
It doesn't work I think it's the server https://pandanite.net/ which often has problems I had to wait 1 day before I could connect to my wallet.
![Screenshot 2023-06-08 222530](https://github.com/pandanite-crypto/pandanite-wallet/assets/72951793/6cd0a17b-48f4-4b9c-9d7a-fa02c7fe3207)
